### PR TITLE
The Isle Evrima Dedicated Server

### PR DESCRIPTION
**Pull request by dkdue**
Add Dedicated Server for The Isle Evrima Beta

### CODE REVIEW

**Comment by BattlefieldDuck** [comment]
Thanks for your contribution. I had looked into the code, I believe that the server can be supported by a plugin instead of direct implementation. I hope the game servers can be supported by plugins instead of hardcoded inside WindowsGSM.

**Comment by dkdue** [comment]
It works perfectly as a plugin, but I have decided to incorporate it to implement it in the dashboard, the plugin does not show connected players and if you implement it everything looks perfect.

**Comment by BattlefieldDuck** [comment]
The game server will be displayed in the dashboard if the `QueryMethod` is functional is set properly.

**Comment by dkdue** [comment]
ok ok

**Pull request closed without merging**
